#
# Makefile to build Athenz Server RDL Code Generator
# Prerequisite: Go development environment
#
# Copyright The Athenz Authors
# Licensed under the Apache License, Version 2.0 - http://www.apache.org/licenses/LICENSE-2.0
#

all:
	@echo "Building Athenz Server RDL generator..."
	@./make_generator.sh

clean:
	rm -rf rdl-gen-athenz-server
