{{- if (not .Values.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "athenz-zms.secretName" . }}
  labels:
    app: "{{ template "athenz-zms.name" . }}"
    chart: "{{ template "athenz-zms.chart" . }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
type: Opaque
data:
  zms_private.pem: {{ .Files.Get .Values.files.zmsKey | b64enc | nindent 4 }}
  jdbc: {{ .Values.password.jdbc | b64enc | quote }}
  jdbcRo: {{ .Values.password.jdbcRo | b64enc | quote }}
  keystore: {{ .Values.password.keystore | default (randAlphaNum 32) | b64enc | quote }}
  truststore: {{ .Values.password.truststore | default (randAlphaNum 32) | b64enc | quote }}
---
{{- end -}}

{{- if and (not .Values.existingTLSSecret) (not .Values.existingTLSStoreSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "athenz-zms.tls.secretName" . }}
  labels:
    app: "{{ template "athenz-zms.name" . }}"
    chart: "{{ template "athenz-zms.chart" . }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Files.Get .Values.files.tls.crt | b64enc | nindent 4 }}
  tls.key: {{ .Files.Get .Values.files.tls.key | b64enc | nindent 4 }}
---
{{- end -}}
{{- if and (not .Values.existingTLSCASecret) (not .Values.existingTLSStoreSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "athenz-zms.tls.ca.secretName" . }}
  labels:
    app: "{{ template "athenz-zms.name" . }}"
    chart: "{{ template "athenz-zms.chart" . }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
type: Opaque
data:
  {{- $files := .Files }}
  {{- range .Values.files.tls.ca }}
    {{ base . }}: {{ $files.Get . | b64enc }}
  {{- end }}
{{- end -}}
