#
# Makefile to build Athenz Java Client RDL Code Generator
# Prerequisite: Go development environment
#
# Copyright The Athenz Authors
# Licensed under the Apache License, Version 2.0 - http://www.apache.org/licenses/LICENSE-2.0
#

all:
	@echo "Building Athenz Java Model RDL generator..."
	@./make_generator.sh

clean:
	rm -rf rdl-gen-athenz-java-model
