# Copyright Verizon Media. Licensed under the terms of the Apache 2.0 license. See LICENSE in the project root.
---
cache:
  job:
    main: [/main_job_cache]

jobs:
  main:
    requires: [~pr, ~commit]
    image: maven:3.6.3-openjdk-8
    screwdriver.cd/cpu: 8
    screwdriver.cd/ram: 16
    screwdriver.cd/disk: HIGH
    screwdriver.cd/timeout: 600

    steps:
      - install_dependencies: "screwdriver/scripts/install_deps.sh"
      - pre_build: "screwdriver/scripts/prepare_build.sh"
      - build: "screwdriver/scripts/build.sh"
      - publish: "screwdriver/scripts/publish.sh"
