# Copyright Verizon Media. Licensed under the terms of the Apache 2.0 license. See LICENSE in the project root.
---

shared:
  image: openjdk:8
  annotations:
    screwdriver.cd/cpu: 8
    screwdriver.cd/ram: 16
    screwdriver.cd/disk: HIGH
    screwdriver.cd/timeout: 120
  environment:
    USER_SHELL_BIN: /bin/bash
  
jobs:
  pull-request:
    requires: [~pr]
    steps:
      - install_dependencies: "screwdriver/scripts/install_deps.sh"
      - build: "screwdriver/scripts/build.sh"

  main:
    requires: [~commit]
    steps:
      - install_dependencies: "screwdriver/scripts/install_deps.sh"
      - build: "screwdriver/scripts/build.sh"

#  publish:
#    requires: [~tag]
#    steps:
#      - install_dependencies: "screwdriver/scripts/install_deps.sh"
#      - build: "screwdriver/scripts/build.sh"
#      - publish: "screwdriver/scripts/publish.sh"
#    secrets:
#      - OSSRH_USER
#      - OSSRH_TOKEN
