# Copyright Verizon Media. Licensed under the terms of the Apache 2.0 license. See LICENSE in the project root.
---
cache:
  job:
    main: [/main_job_cache]

jobs:
  main:
    requires: [~pr, ~commit]
    image: openjdk-8
    annotations:
      screwdriver.cd/cpu: 8
      screwdriver.cd/ram: 16
      screwdriver.cd/disk: HIGH
      screwdriver.cd/timeout: 600

    steps:
      - prepare_dev: "/screwdriver/scripts/prepare_dev.sh"
      - build: mvn install
      - publish: "/screwdriver/scripts/publish.sh"
