#!/bin/bash

usage() {
    echo "Usage: athenz_ui (start | stop)"
}

if [ $# -ne 1 ]
then
    echo "Invalid number of arguments specified"
    usage
    exit 1
fi

# verify that node and nodemon are included in our path

command -v node >/dev/null 2>&1 || {
    echo "Please make sure node binary is included in your runtime path"
    exit 1;
}

command -v nodemon >/dev/null 2>&1 || {
    echo "Please make sure nodemon binary is included in your runtime path"
    exit 1;
}

# make sure we have our required environment variables
# defined before starting the ui server

if [ -z "${UI_SERVER}" ]; then
    echo "Please export UI_SERVER environment variable pointing to your UI Server Hostname"
    exit 1
fi

if [ -z "${ZMS_SERVER}" ]; then
    echo "Please export ZMS_SERVER environment variable pointing to your ZMS Server Hostname"
    exit 1
fi

# if ZMS_SERVER_URL is not found in the environment, then we are going to generate
# ZMS_SERVER_URL based on the ZMS_SERVER environment variable, otherwise we will use the
# ZMS_SERVER_URL as-is.
if [ -z "${ZMS_SERVER_URL}" ]; then
    export ZMS_SERVER_URL=https://${ZMS_SERVER}:4443/zms/v1/
fi
if [ -z "${ZMS_LOGIN_URL}" ]; then
    export ZMS_LOGIN_URL=https://${ZMS_SERVER}:4443/zms/v1/
fi
if [ -z "${ZMS_CONNECT_SRC_URL}" ]; then
    export ZMS_CONNECT_SRC_URL=https://${ZMS_SERVER}:4443
fi
# if we don't have ROOT variable defined we'll default
# to the parent directory where the script is running from

if [ -z "${ROOT}" ]; then
    BINDIR=$(dirname "$0")
    export "ROOT"=$(cd "$BINDIR"/.. || true;pwd)
fi

ATHENZ_UI_PID_DIR=${ATHENZ_UI_PID_DIR:-$ROOT/var/ui}
ATHENZ_UI_LOG_DIR=${ATHENZ_UI_LOG_DIR:-$ROOT/logs/ui}

# make sure our pid and log directories exist

mkdir -p "${ATHENZ_UI_PID_DIR}"
mkdir -p "${ATHENZ_UI_LOG_DIR}"

command=$1

pid=${ATHENZ_UI_PID_DIR}/ui.pid
log=${ATHENZ_UI_LOG_DIR}/ui.out

case $command in
    (start)
        if [ -f $pid ]; then
            ATHENZ_UI_PID=$(cat "$pid")
            if kill -0 "${ATHENZ_UI_PID}" > /dev/null 2>&1; then
                echo "Athenz UI already running as process ${ATHENZ_UI_PID}"
                exit 1
            fi
        fi

        echo "Starting Athenz UI..."
        nohup nodemon -r dotenv/config app.js > "$log" 2>&1 < /dev/null &
        echo $! > "$pid"
        sleep 2;
        if ! ps -p $! > /dev/null ; then
            exit 1
        fi
    ;;

    (stop)
        if [ -f $pid ]; then
            ATHENZ_UI_PID=$(cat "$pid")
            if kill -0 "${ATHENZ_UI_PID}" > /dev/null 2>&1; then
                echo "Stopping Athenz UI..."
                ATHENZ_UI_GPID=$(ps -o pgid= "$ATHENZ_UI_PID" | grep -o '[0-9]*')
                kill -9 -"${ATHENZ_UI_GPID}"
                echo "Shutdown completed."
            else
                echo "Athenz UI is not running"
            fi
            rm "$pid"
        else
            echo "Athenz UI is not running"
        fi
    ;;

    (*)
        usage
        exit 1
    ;;
esac
