//
// This file generated by rdl 1.5.2. Do not modify!
//

package com.yahoo.athenz.zts;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import java.util.Map;
import com.yahoo.rdl.*;

//
// ExternalCredentialsRequest -
//
@JsonIgnoreProperties(ignoreUnknown = true)
public class ExternalCredentialsRequest {
    public String clientId;
    @RdlOptional
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    public Integer expiryTime;
    @RdlOptional
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    public Map<String, String> attributes;

    public ExternalCredentialsRequest setClientId(String clientId) {
        this.clientId = clientId;
        return this;
    }
    public String getClientId() {
        return clientId;
    }
    public ExternalCredentialsRequest setExpiryTime(Integer expiryTime) {
        this.expiryTime = expiryTime;
        return this;
    }
    public Integer getExpiryTime() {
        return expiryTime;
    }
    public ExternalCredentialsRequest setAttributes(Map<String, String> attributes) {
        this.attributes = attributes;
        return this;
    }
    public Map<String, String> getAttributes() {
        return attributes;
    }

    @Override
    public boolean equals(Object another) {
        if (this != another) {
            if (another == null || another.getClass() != ExternalCredentialsRequest.class) {
                return false;
            }
            ExternalCredentialsRequest a = (ExternalCredentialsRequest) another;
            if (clientId == null ? a.clientId != null : !clientId.equals(a.clientId)) {
                return false;
            }
            if (expiryTime == null ? a.expiryTime != null : !expiryTime.equals(a.expiryTime)) {
                return false;
            }
            if (attributes == null ? a.attributes != null : !attributes.equals(a.attributes)) {
                return false;
            }
        }
        return true;
    }
}
