//
// This file generated by rdl 1.5.2. Do not modify!
//

package com.yahoo.athenz.zts;
import com.yahoo.rdl.*;

//
// OSTKInstanceInformation - Instance object that includes requested service
// details plus host document that is signed by Openstack as part of the host
// bootstrap process
//
public class OSTKInstanceInformation {
    public String document;
    public String signature;
    public String keyId;
    public String domain;
    public String service;
    public String csr;

    public OSTKInstanceInformation setDocument(String document) {
        this.document = document;
        return this;
    }
    public String getDocument() {
        return document;
    }
    public OSTKInstanceInformation setSignature(String signature) {
        this.signature = signature;
        return this;
    }
    public String getSignature() {
        return signature;
    }
    public OSTKInstanceInformation setKeyId(String keyId) {
        this.keyId = keyId;
        return this;
    }
    public String getKeyId() {
        return keyId;
    }
    public OSTKInstanceInformation setDomain(String domain) {
        this.domain = domain;
        return this;
    }
    public String getDomain() {
        return domain;
    }
    public OSTKInstanceInformation setService(String service) {
        this.service = service;
        return this;
    }
    public String getService() {
        return service;
    }
    public OSTKInstanceInformation setCsr(String csr) {
        this.csr = csr;
        return this;
    }
    public String getCsr() {
        return csr;
    }

    @Override
    public boolean equals(Object another) {
        if (this != another) {
            if (another == null || another.getClass() != OSTKInstanceInformation.class) {
                return false;
            }
            OSTKInstanceInformation a = (OSTKInstanceInformation) another;
            if (document == null ? a.document != null : !document.equals(a.document)) {
                return false;
            }
            if (signature == null ? a.signature != null : !signature.equals(a.signature)) {
                return false;
            }
            if (keyId == null ? a.keyId != null : !keyId.equals(a.keyId)) {
                return false;
            }
            if (domain == null ? a.domain != null : !domain.equals(a.domain)) {
                return false;
            }
            if (service == null ? a.service != null : !service.equals(a.service)) {
                return false;
            }
            if (csr == null ? a.csr != null : !csr.equals(a.csr)) {
                return false;
            }
        }
        return true;
    }
}
