//
// This file generated by rdl 1.5.1. Do not modify!
//

package com.yahoo.athenz.zts;
import com.yahoo.rdl.*;

//
// SSHCertRequest -
//
public class SSHCertRequest {
    public SSHCertRequestData certRequestData;
    public SSHCertRequestMeta certRequestMeta;

    public SSHCertRequest setCertRequestData(SSHCertRequestData certRequestData) {
        this.certRequestData = certRequestData;
        return this;
    }
    public SSHCertRequestData getCertRequestData() {
        return certRequestData;
    }
    public SSHCertRequest setCertRequestMeta(SSHCertRequestMeta certRequestMeta) {
        this.certRequestMeta = certRequestMeta;
        return this;
    }
    public SSHCertRequestMeta getCertRequestMeta() {
        return certRequestMeta;
    }

    @Override
    public boolean equals(Object another) {
        if (this != another) {
            if (another == null || another.getClass() != SSHCertRequest.class) {
                return false;
            }
            SSHCertRequest a = (SSHCertRequest) another;
            if (certRequestData == null ? a.certRequestData != null : !certRequestData.equals(a.certRequestData)) {
                return false;
            }
            if (certRequestMeta == null ? a.certRequestMeta != null : !certRequestMeta.equals(a.certRequestMeta)) {
                return false;
            }
        }
        return true;
    }
}
