//
// This file generated by rdl 1.5.2. Do not modify!
//

package com.yahoo.athenz.zts;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.yahoo.rdl.*;

//
// UserCertificate - Copyright The Athenz Authors Licensed under the terms of
// the Apache version 2.0 license. See LICENSE file for terms. UserCertificate -
// a user certificate
//
@JsonIgnoreProperties(ignoreUnknown = true)
public class UserCertificate {
    public String x509Certificate;

    public UserCertificate setX509Certificate(String x509Certificate) {
        this.x509Certificate = x509Certificate;
        return this;
    }
    public String getX509Certificate() {
        return x509Certificate;
    }

    @Override
    public boolean equals(Object another) {
        if (this != another) {
            if (another == null || another.getClass() != UserCertificate.class) {
                return false;
            }
            UserCertificate a = (UserCertificate) another;
            if (x509Certificate == null ? a.x509Certificate != null : !x509Certificate.equals(a.x509Certificate)) {
                return false;
            }
        }
        return true;
    }
}
