//
// This file generated by rdl 1.5.2. Do not modify!
//

package com.yahoo.athenz.zts;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import java.util.List;
import com.yahoo.rdl.*;

//
// Workloads -
//
@JsonIgnoreProperties(ignoreUnknown = true)
public class Workloads {
    public List<Workload> workloadList;

    public Workloads setWorkloadList(List<Workload> workloadList) {
        this.workloadList = workloadList;
        return this;
    }
    public List<Workload> getWorkloadList() {
        return workloadList;
    }

    @Override
    public boolean equals(Object another) {
        if (this != another) {
            if (another == null || another.getClass() != Workloads.class) {
                return false;
            }
            Workloads a = (Workloads) another;
            if (workloadList == null ? a.workloadList != null : !workloadList.equals(a.workloadList)) {
                return false;
            }
        }
        return true;
    }
}
