{{- if (not .Values.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "athenz-zts.secretName" . }}
  labels:
    app: "{{ template "athenz-zts.name" . }}"
    chart: "{{ template "athenz-zts.chart" . }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
type: Opaque
data:
  zts_private.pem: {{ .Files.Get .Values.files.ztsKey | b64enc | nindent 4 }}
  jdbc: {{ .Values.password.jdbc | b64enc | quote }}
  keystore: {{ .Values.password.keystore | default (randAlphaNum 32) | b64enc | quote }}
  truststore: {{ .Values.password.truststore | default (randAlphaNum 32) | b64enc | quote }}
  signerKeystore: {{ .Values.password.signerKeystore | default (randAlphaNum 32) | b64enc | quote }}
  signerTruststore: {{ .Values.password.signerTruststore | default (randAlphaNum 32) | b64enc | quote }}
  zmsClientKeystore: {{ .Values.password.zmsClientKeystore | default (randAlphaNum 32) | b64enc | quote }}
  zmsClientTruststore: {{ .Values.password.zmsClientTruststore | default (randAlphaNum 32) | b64enc | quote }}
---
{{- end -}}

{{- if and (not .Values.existingZMSClientSecret) (not .Values.existingZMSClientStoreSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "athenz-zts.zmsClient.secretName" . }}
  labels:
    app: "{{ template "athenz-zts.name" . }}"
    chart: "{{ template "athenz-zts.chart" . }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Files.Get .Values.files.zmsClient.crt | b64enc | nindent 4 }}
  tls.key: {{ .Files.Get .Values.files.zmsClient.key | b64enc | nindent 4 }}
---
{{- end -}}
{{- if and (not .Values.existingZMSClientCASecret) (not .Values.existingZMSClientStoreSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "athenz-zts.zmsClient.ca.secretName" . }}
  labels:
    app: "{{ template "athenz-zts.name" . }}"
    chart: "{{ template "athenz-zts.chart" . }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
type: Opaque
data:
  {{- $files := .Files }}
  {{- range .Values.files.zmsClient.ca }}
    {{ base . }}: {{ $files.Get . | b64enc }}
  {{- end }}
---
{{- end -}}

{{- if and (not .Values.existingSignerSecret) (not .Values.existingSignerStoreSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "athenz-zts.signer.secretName" . }}
  labels:
    app: "{{ template "athenz-zts.name" . }}"
    chart: "{{ template "athenz-zts.chart" . }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Files.Get .Values.files.signer.crt | b64enc | nindent 4 }}
  tls.key: {{ .Files.Get .Values.files.signer.key | b64enc | nindent 4 }}
---
{{- end -}}
{{- if and (not .Values.existingSignerCASecret) (not .Values.existingSignerStoreSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "athenz-zts.signer.ca.secretName" . }}
  labels:
    app: "{{ template "athenz-zts.name" . }}"
    chart: "{{ template "athenz-zts.chart" . }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
type: Opaque
data:
  {{- $files := .Files }}
  {{- range .Values.files.signer.ca }}
    {{ base . }}: {{ $files.Get . | b64enc }}
  {{- end }}
---
{{- end -}}

{{- if and (not .Values.existingTLSSecret) (not .Values.existingTLSStoreSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "athenz-zts.tls.secretName" . }}
  labels:
    app: "{{ template "athenz-zts.name" . }}"
    chart: "{{ template "athenz-zts.chart" . }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Files.Get .Values.files.tls.crt | b64enc | nindent 4 }}
  tls.key: {{ .Files.Get .Values.files.tls.key | b64enc | nindent 4 }}
---
{{- end -}}
{{- if and (not .Values.existingTLSCASecret) (not .Values.existingTLSStoreSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "athenz-zts.tls.ca.secretName" . }}
  labels:
    app: "{{ template "athenz-zts.name" . }}"
    chart: "{{ template "athenz-zts.chart" . }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
type: Opaque
data:
  {{- $files := .Files }}
  {{- range .Values.files.tls.ca }}
    {{ base . }}: {{ $files.Get . | b64enc }}
  {{- end }}
{{- end -}}
