#!/usr/bin/env bash

# list of authorities for authenticating principals
CONTAINER_AUTHORITY_CLASSES="com.yahoo.athenz.auth.impl.PrincipalAuthority,com.yahoo.athenz.auth.impl.UserAuthority"

# private/public key pair for zts instance - must be generated
# using with default key id of 0
CONTAINER_PRIVKEY="${ROOT}/var/zts_server/keys/zts_private.pem"
CONTAINER_PRIVKEY_ID="0"
# CONTAINER_PRIVATE_KEY_STORE_FACTORY_CLASS=com.yahoo.athenz.auth.impl.FilePrivateKeyStoreFactory

# default ports for zts server. http support is disabled
# https support enabled - must provide certificate for server
CONTAINER_TLS_PORT="8443"
CONTAINER_PORT="0"

# setup the keystore in pkcs12 format that includes our
# server's private key and x509 cert
CONTAINER_SSL_KEYSTORE="${ROOT}/var/zts_server/certs/zts_keystore.pkcs12"
CONTAINER_SSL_KEYSTORE_TYPE="PKCS12"
CONTAINER_SSL_KEYSTORE_PASSWORD="athenz"

CONTAINER_SSL_TRUSTSTORE="${ROOT}/var/zts_server/certs/zts_truststore.jks"
CONTAINER_SSL_TRUSTSTORE_TYPE="JKS"
CONTAINER_SSL_TRUSTSTORE_PASSWORD="athenz"

# ** athenz configuration file
CONTAINER_ATHENZ_CONF="conf/zts_server/athenz.conf"

# ** logback configuration file
CONTAINER_LOG_CONFIG="${ROOT}/conf/zts_server/logback.xml"

# ** we're going to use self signer class
CONTAINER_CERT_SIGNER_FACTORY_CLASS="com.yahoo.athenz.zts.cert.impl.SelfCertSignerFactory"
CONTAINER_SELF_SIGNER_PRIVATE_KEY_FNAME="${ROOT}/var/zts_server/keys/zts_private.pem"

# ** server settings

# CONTAINER_LISTEN_HOST=
# CONTAINER_HOSTNAME=
# CONTAINER_ROLE_TOKEN_MAX_TIMEOUT=
# CONTAINER_ROLE_TOKEN_DEFAULT_TIMEOUT=
# CONTAINER_SIGNED_POLICY_TIMEOUT=
# CONTAINER_ZMS_DOMAIN_UPDATE_TIMEOUT=
# CONTAINER_ZMS_DOMAIN_DELETE_TIMEOUT=
# CONTAINER_ZMS_CLIENT_READ_TIMEOUT=

# ** list of authorized proxy users
# CONTAINER_AUTHZ_PROXY_USERS=

# ** more ssl settings
# CONTAINER_SSL_KEYMANAGER_PASSWORD=
# CONTAINER_SSL_EXCLUDED_CIPHER_SUITES=
# CONTAINER_SSL_EXCLUDED_PROTOCOLS=

# ** access log settings
# CONTAINER_ACCESS_LOG_DIR=
# CONTAINER_ACCESS_LOG_NAME=
# CONTAINER_ACCESS_LOG_OPTIONS=
# CONTAINER_ACCESS_LOG_RETAIN_DAYS=
# CONTAINER_ACCESS_LOG_ROTATION_PERIOD=
# CONTAINER_ACCESS_LOG_ROTATION_UNIT=

# ** configure what implementation classes to use
# CONTAINER_DATA_CHANGE_LOG_STORE_FACTORY_CLASS=
# CONTAINER_HOST_SIGNER_SERVICE=
# CONTAINER_CERTSIGN_BASE_URI=

# ** kerberos authority settings
# CONTAINER_KRB_KEYTAB=
# CONTAINER_KRB_PRINCIPAL=
# CONTAINER_KRB_TKT_CACHE=
# CONTAINER_KRB_TKT_CACHE_PATH=
# CONTAINER_KRB_TGT_RENEW=
# CONTAINER_KRB_DEBUG=
# CONTAINER_KRB_JAAS_CONF=
