//
// This file generated by rdl 1.5.2. Do not modify!
//

package com.yahoo.athenz.msd;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import java.util.List;
import com.yahoo.rdl.*;

//
// BulkWorkloadRequest - request type to search all workloads for a list of
// services grouped by domains
//
@JsonIgnoreProperties(ignoreUnknown = true)
public class BulkWorkloadRequest {
    public List<DomainServices> domainServices;
    @RdlOptional
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    public Boolean fetchStaticTypeWorkloads;
    @RdlOptional
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    public Boolean fetchDynamicTypeWorkloads;
    @RdlOptional
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    public List<StaticWorkloadType> applicableStaticTypes;
    @RdlOptional
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    public Boolean resolveStaticWorkloads;

    public BulkWorkloadRequest setDomainServices(List<DomainServices> domainServices) {
        this.domainServices = domainServices;
        return this;
    }
    public List<DomainServices> getDomainServices() {
        return domainServices;
    }
    public BulkWorkloadRequest setFetchStaticTypeWorkloads(Boolean fetchStaticTypeWorkloads) {
        this.fetchStaticTypeWorkloads = fetchStaticTypeWorkloads;
        return this;
    }
    public Boolean getFetchStaticTypeWorkloads() {
        return fetchStaticTypeWorkloads;
    }
    public BulkWorkloadRequest setFetchDynamicTypeWorkloads(Boolean fetchDynamicTypeWorkloads) {
        this.fetchDynamicTypeWorkloads = fetchDynamicTypeWorkloads;
        return this;
    }
    public Boolean getFetchDynamicTypeWorkloads() {
        return fetchDynamicTypeWorkloads;
    }
    public BulkWorkloadRequest setApplicableStaticTypes(List<StaticWorkloadType> applicableStaticTypes) {
        this.applicableStaticTypes = applicableStaticTypes;
        return this;
    }
    public List<StaticWorkloadType> getApplicableStaticTypes() {
        return applicableStaticTypes;
    }
    public BulkWorkloadRequest setResolveStaticWorkloads(Boolean resolveStaticWorkloads) {
        this.resolveStaticWorkloads = resolveStaticWorkloads;
        return this;
    }
    public Boolean getResolveStaticWorkloads() {
        return resolveStaticWorkloads;
    }

    @Override
    public boolean equals(Object another) {
        if (this != another) {
            if (another == null || another.getClass() != BulkWorkloadRequest.class) {
                return false;
            }
            BulkWorkloadRequest a = (BulkWorkloadRequest) another;
            if (domainServices == null ? a.domainServices != null : !domainServices.equals(a.domainServices)) {
                return false;
            }
            if (fetchStaticTypeWorkloads == null ? a.fetchStaticTypeWorkloads != null : !fetchStaticTypeWorkloads.equals(a.fetchStaticTypeWorkloads)) {
                return false;
            }
            if (fetchDynamicTypeWorkloads == null ? a.fetchDynamicTypeWorkloads != null : !fetchDynamicTypeWorkloads.equals(a.fetchDynamicTypeWorkloads)) {
                return false;
            }
            if (applicableStaticTypes == null ? a.applicableStaticTypes != null : !applicableStaticTypes.equals(a.applicableStaticTypes)) {
                return false;
            }
            if (resolveStaticWorkloads == null ? a.resolveStaticWorkloads != null : !resolveStaticWorkloads.equals(a.resolveStaticWorkloads)) {
                return false;
            }
        }
        return true;
    }

    //
    // sets up the instance according to its default field values, if any
    //
    public BulkWorkloadRequest init() {
        if (fetchStaticTypeWorkloads == null) {
            fetchStaticTypeWorkloads = true;
        }
        if (fetchDynamicTypeWorkloads == null) {
            fetchDynamicTypeWorkloads = true;
        }
        if (resolveStaticWorkloads == null) {
            resolveStaticWorkloads = false;
        }
        return this;
    }
}
