//
// This file generated by rdl 1.5.2. Do not modify!
//

package com.yahoo.athenz.msd;
import com.yahoo.rdl.*;

//
// TransportPolicyProtocol - Types of transport policy protocols
//
public enum TransportPolicyProtocol {
    TCP,
    UDP;

    public static TransportPolicyProtocol fromString(String v) {
        for (TransportPolicyProtocol e : values()) {
            if (e.toString().equals(v)) {
                return e;
            }
        }
        throw new IllegalArgumentException("Invalid string representation for TransportPolicyProtocol: " + v);
    }
}
