//
// This file generated by rdl 1.5.2. Do not modify!
//

package com.yahoo.athenz.msd;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import java.util.List;
import com.yahoo.rdl.*;

//
// TransportPolicySnapshotUsage - Usage recorded for a snapshot - which
// principals last used it, and when
//
@JsonIgnoreProperties(ignoreUnknown = true)
public class TransportPolicySnapshotUsage {
    public List<TransportPolicySnapshotUsagePrincipal> principals;
    @RdlOptional
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    public Boolean partial;
    @RdlOptional
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    public TransportPolicySnapshotUsageWarning warning;

    public TransportPolicySnapshotUsage setPrincipals(List<TransportPolicySnapshotUsagePrincipal> principals) {
        this.principals = principals;
        return this;
    }
    public List<TransportPolicySnapshotUsagePrincipal> getPrincipals() {
        return principals;
    }
    public TransportPolicySnapshotUsage setPartial(Boolean partial) {
        this.partial = partial;
        return this;
    }
    public Boolean getPartial() {
        return partial;
    }
    public TransportPolicySnapshotUsage setWarning(TransportPolicySnapshotUsageWarning warning) {
        this.warning = warning;
        return this;
    }
    public TransportPolicySnapshotUsageWarning getWarning() {
        return warning;
    }

    @Override
    public boolean equals(Object another) {
        if (this != another) {
            if (another == null || another.getClass() != TransportPolicySnapshotUsage.class) {
                return false;
            }
            TransportPolicySnapshotUsage a = (TransportPolicySnapshotUsage) another;
            if (principals == null ? a.principals != null : !principals.equals(a.principals)) {
                return false;
            }
            if (partial == null ? a.partial != null : !partial.equals(a.partial)) {
                return false;
            }
            if (warning == null ? a.warning != null : !warning.equals(a.warning)) {
                return false;
            }
        }
        return true;
    }
}
