//
// This file generated by rdl 1.5.2. Do not modify!
//

package com.yahoo.athenz.msd;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.yahoo.rdl.*;

//
// TransportPolicySnapshotRequest - Request to create a new transport policy
// snapshot
//
@JsonIgnoreProperties(ignoreUnknown = true)
public class TransportPolicySnapshotRequest {
    public String name;
    public boolean active;

    public TransportPolicySnapshotRequest setName(String name) {
        this.name = name;
        return this;
    }
    public String getName() {
        return name;
    }
    public TransportPolicySnapshotRequest setActive(boolean active) {
        this.active = active;
        return this;
    }
    public boolean getActive() {
        return active;
    }

    @Override
    public boolean equals(Object another) {
        if (this != another) {
            if (another == null || another.getClass() != TransportPolicySnapshotRequest.class) {
                return false;
            }
            TransportPolicySnapshotRequest a = (TransportPolicySnapshotRequest) another;
            if (name == null ? a.name != null : !name.equals(a.name)) {
                return false;
            }
            if (active != a.active) {
                return false;
            }
        }
        return true;
    }
}
