//
// This file generated by rdl 1.5.2. Do not modify!
//

package com.yahoo.athenz.msd;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.yahoo.rdl.*;

//
// TransportPolicySubject - Subject for a transport policy
//
@JsonIgnoreProperties(ignoreUnknown = true)
public class TransportPolicySubject {
    public String domainName;
    public String serviceName;

    public TransportPolicySubject setDomainName(String domainName) {
        this.domainName = domainName;
        return this;
    }
    public String getDomainName() {
        return domainName;
    }
    public TransportPolicySubject setServiceName(String serviceName) {
        this.serviceName = serviceName;
        return this;
    }
    public String getServiceName() {
        return serviceName;
    }

    @Override
    public boolean equals(Object another) {
        if (this != another) {
            if (another == null || another.getClass() != TransportPolicySubject.class) {
                return false;
            }
            TransportPolicySubject a = (TransportPolicySubject) another;
            if (domainName == null ? a.domainName != null : !domainName.equals(a.domainName)) {
                return false;
            }
            if (serviceName == null ? a.serviceName != null : !serviceName.equals(a.serviceName)) {
                return false;
            }
        }
        return true;
    }
}
