//
// This file generated by rdl 1.5.2. Do not modify!
//

package com.yahoo.athenz.msd;
import com.yahoo.rdl.*;

//
// TransportPolicyValidationStatus - Validation Status of transport policy vs
// network policy
//
public enum TransportPolicyValidationStatus {
    VALID,
    INVALID,
    PARTIAL;

    public static TransportPolicyValidationStatus fromString(String v) {
        for (TransportPolicyValidationStatus e : values()) {
            if (e.toString().equals(v)) {
                return e;
            }
        }
        throw new IllegalArgumentException("Invalid string representation for TransportPolicyValidationStatus: " + v);
    }
}
