//
// This file generated by rdl 1.5.2. Do not modify!
//

package com.yahoo.athenz.msd;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import java.util.List;
import com.yahoo.rdl.*;

//
// TransportPolicyEntitySelector - Entity to which a transport policy applies.
// Describes the subject and port(s) for a transport policy.
//
@JsonIgnoreProperties(ignoreUnknown = true)
public class TransportPolicyEntitySelector {
    public TransportPolicyMatch match;
    public List<TransportPolicyPort> ports;

    public TransportPolicyEntitySelector setMatch(TransportPolicyMatch match) {
        this.match = match;
        return this;
    }
    public TransportPolicyMatch getMatch() {
        return match;
    }
    public TransportPolicyEntitySelector setPorts(List<TransportPolicyPort> ports) {
        this.ports = ports;
        return this;
    }
    public List<TransportPolicyPort> getPorts() {
        return ports;
    }

    @Override
    public boolean equals(Object another) {
        if (this != another) {
            if (another == null || another.getClass() != TransportPolicyEntitySelector.class) {
                return false;
            }
            TransportPolicyEntitySelector a = (TransportPolicyEntitySelector) another;
            if (match == null ? a.match != null : !match.equals(a.match)) {
                return false;
            }
            if (ports == null ? a.ports != null : !ports.equals(a.ports)) {
                return false;
            }
        }
        return true;
    }
}
