//
// This file generated by rdl 1.5.2. Do not modify!
//

package com.yahoo.athenz.msd;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import java.util.List;
import com.yahoo.rdl.*;

//
// TransportPolicySnapshots - List of transport policy snapshot metadata
//
@JsonIgnoreProperties(ignoreUnknown = true)
public class TransportPolicySnapshots {
    public List<TransportPolicySnapshotMetadata> snapshots;

    public TransportPolicySnapshots setSnapshots(List<TransportPolicySnapshotMetadata> snapshots) {
        this.snapshots = snapshots;
        return this;
    }
    public List<TransportPolicySnapshotMetadata> getSnapshots() {
        return snapshots;
    }

    @Override
    public boolean equals(Object another) {
        if (this != another) {
            if (another == null || another.getClass() != TransportPolicySnapshots.class) {
                return false;
            }
            TransportPolicySnapshots a = (TransportPolicySnapshots) another;
            if (snapshots == null ? a.snapshots != null : !snapshots.equals(a.snapshots)) {
                return false;
            }
        }
        return true;
    }
}
