prettyPrint: true
openAPI:
  info:
    version: '1.0.0'
    title: 'ZMS Swagger'
  servers:
    - url: /devapi
      description: Development ZMS server
    - url: /stageapi
      description: Staging ZMS server
    - url: /prodapi
      description: Production ZMS server