apiVersion: v1
entries:
  athenz-zms:
  - apiVersion: v2
    appVersion: 1.9.27
    created: "2020-12-22T18:18:13.483208+09:00"
    description: Athenz is a role-based authorization (RBAC) system for provisioning
      and configuration (centralized authorization) use cases as well as serving/runtime
      (decentralized authorization) use cases.
    digest: 6cbcfbef4b30ece24868808cbc18b2d25a7cc2f012d3d370d4de396fce9186bb
    home: https://www.athenz.io
    icon: https://raw.githubusercontent.com/AthenZ/athenz/master/docs/images/athenz-logo-line.svg
    keywords:
    - athenz
    - RBAC
    - authorization
    kubeVersion: '>=1.16.0-0'
    maintainers:
    - email: windz.athenz@gmail.com
      name: Windz
      url: https://github.com/WindzCUHK
    name: athenz-zms
    sources:
    - https://github.com/AthenZ/athenz
    urls:
    - https://raw.githubusercontent.com/AthenZ/athenz/master/kubernetes/charts/athenz-zms-1.0.0.tgz
    version: 1.0.0
  athenz-zts:
  - apiVersion: v2
    appVersion: 1.9.27
    created: "2020-12-22T18:18:13.485685+09:00"
    description: Athenz is a role-based authorization (RBAC) system for provisioning
      and configuration (centralized authorization) use cases as well as serving/runtime
      (decentralized authorization) use cases.
    digest: 6d38a2238c6548b0f864e85c74bd55d7c34a735907e422f79f70243ae2075e00
    home: https://www.athenz.io
    icon: https://raw.githubusercontent.com/AthenZ/athenz/master/docs/images/athenz-logo-line.svg
    keywords:
    - athenz
    - RBAC
    - authorization
    kubeVersion: '>=1.16.0-0'
    maintainers:
    - email: windz.athenz@gmail.com
      name: Windz
      url: https://github.com/WindzCUHK
    name: athenz-zts
    sources:
    - https://github.com/AthenZ/athenz
    urls:
    - https://raw.githubusercontent.com/AthenZ/athenz/master/kubernetes/charts/athenz-zts-1.0.0.tgz
    version: 1.0.0
generated: "2020-12-22T18:18:13.480111+09:00"
