//
// This file generated by rdl 1.5.2. Do not modify!
//

package com.yahoo.athenz.zms;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.yahoo.rdl.*;

//
// DanglingPolicy - A dangling policy where the assertion is referencing a role
// name that doesn't exist in the domain
//
@JsonIgnoreProperties(ignoreUnknown = true)
public class DanglingPolicy {
    public String policyName;
    public String roleName;

    public DanglingPolicy setPolicyName(String policyName) {
        this.policyName = policyName;
        return this;
    }
    public String getPolicyName() {
        return policyName;
    }
    public DanglingPolicy setRoleName(String roleName) {
        this.roleName = roleName;
        return this;
    }
    public String getRoleName() {
        return roleName;
    }

    @Override
    public boolean equals(Object another) {
        if (this != another) {
            if (another == null || another.getClass() != DanglingPolicy.class) {
                return false;
            }
            DanglingPolicy a = (DanglingPolicy) another;
            if (policyName == null ? a.policyName != null : !policyName.equals(a.policyName)) {
                return false;
            }
            if (roleName == null ? a.roleName != null : !roleName.equals(a.roleName)) {
                return false;
            }
        }
        return true;
    }
}
