//
// This file generated by rdl 1.5.2. Do not modify!
//

package com.yahoo.athenz.zms;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import java.util.List;
import com.yahoo.rdl.*;

//
// DependentServiceResourceGroupList -
//
@JsonIgnoreProperties(ignoreUnknown = true)
public class DependentServiceResourceGroupList {
    public List<DependentServiceResourceGroup> serviceAndResourceGroups;

    public DependentServiceResourceGroupList setServiceAndResourceGroups(List<DependentServiceResourceGroup> serviceAndResourceGroups) {
        this.serviceAndResourceGroups = serviceAndResourceGroups;
        return this;
    }
    public List<DependentServiceResourceGroup> getServiceAndResourceGroups() {
        return serviceAndResourceGroups;
    }

    @Override
    public boolean equals(Object another) {
        if (this != another) {
            if (another == null || another.getClass() != DependentServiceResourceGroupList.class) {
                return false;
            }
            DependentServiceResourceGroupList a = (DependentServiceResourceGroupList) another;
            if (serviceAndResourceGroups == null ? a.serviceAndResourceGroups != null : !serviceAndResourceGroups.equals(a.serviceAndResourceGroups)) {
                return false;
            }
        }
        return true;
    }
}
