//
// This file generated by rdl 1.5.2. Do not modify!
//

package com.yahoo.athenz.zms;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.yahoo.rdl.*;

//
// DomainModified - Tuple of domain-name and modification time-stamps. This
// object is returned when the caller has requested list of domains modified
// since a specific timestamp.
//
public class DomainModified {
    public String name;
    public long modified;
    @RdlOptional
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    public String account;
    @RdlOptional
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    public Integer ypmId;

    public DomainModified setName(String name) {
        this.name = name;
        return this;
    }
    public String getName() {
        return name;
    }
    public DomainModified setModified(long modified) {
        this.modified = modified;
        return this;
    }
    public long getModified() {
        return modified;
    }
    public DomainModified setAccount(String account) {
        this.account = account;
        return this;
    }
    public String getAccount() {
        return account;
    }
    public DomainModified setYpmId(Integer ypmId) {
        this.ypmId = ypmId;
        return this;
    }
    public Integer getYpmId() {
        return ypmId;
    }

    @Override
    public boolean equals(Object another) {
        if (this != another) {
            if (another == null || another.getClass() != DomainModified.class) {
                return false;
            }
            DomainModified a = (DomainModified) another;
            if (name == null ? a.name != null : !name.equals(a.name)) {
                return false;
            }
            if (modified != a.modified) {
                return false;
            }
            if (account == null ? a.account != null : !account.equals(a.account)) {
                return false;
            }
            if (ypmId == null ? a.ypmId != null : !ypmId.equals(a.ypmId)) {
                return false;
            }
        }
        return true;
    }
}
