//
// This file generated by rdl 1.5.2. Do not modify!
//

package com.yahoo.athenz.zms;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.yahoo.rdl.*;

//
// Entity - An entity is a name and a structured value. some entity
// names/prefixes are reserved (i.e. "role",  "policy", "meta", "domain",
// "service")
//
@JsonIgnoreProperties(ignoreUnknown = true)
public class Entity {
    public String name;
    public Struct value;

    public Entity setName(String name) {
        this.name = name;
        return this;
    }
    public String getName() {
        return name;
    }
    public Entity setValue(Struct value) {
        this.value = value;
        return this;
    }
    public Struct getValue() {
        return value;
    }

    @Override
    public boolean equals(Object another) {
        if (this != another) {
            if (another == null || another.getClass() != Entity.class) {
                return false;
            }
            Entity a = (Entity) another;
            if (name == null ? a.name != null : !name.equals(a.name)) {
                return false;
            }
            if (value == null ? a.value != null : !value.equals(a.value)) {
                return false;
            }
        }
        return true;
    }
}
