//
// This file generated by rdl 1.4.10. Do not modify!
//

package com.yahoo.athenz.zms;
import com.yahoo.rdl.*;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;

//
// UserToken - A user token generated based on user's credentials
//
@JsonSerialize(include = JsonSerialize.Inclusion.NON_DEFAULT)
public class UserToken {
    public String token;

    public UserToken setToken(String token) {
        this.token = token;
        return this;
    }
    public String getToken() {
        return token;
    }

    @Override
    public boolean equals(Object another) {
        if (this != another) {
            if (another == null || another.getClass() != UserToken.class) {
                return false;
            }
            UserToken a = (UserToken) another;
            if (token == null ? a.token != null : !token.equals(a.token)) {
                return false;
            }
        }
        return true;
    }
}
