#!/usr/bin/env bash

# ** default ports for container. http support is disabled
# ** https support enabled - must provide certificate for server
CONTAINER_TLS_PORT="4443"
CONTAINER_PORT="0"

# ** logback configuration file
CONTAINER_LOG_CONFIG="${ROOT}/conf/athenz/logback.xml"

# ** setup the keystore in pkcs12 format that includes our
# ** server's private key and x509 cert
CONTAINER_SSL_KEYSTORE="file://${ROOT}/var/athenz/certs/zms_keystore.pkcs12"
CONTAINER_SSL_KEYSTORE_TYPE="PKCS12"
CONTAINER_SSL_KEYSTORE_PASSWORD="athenz"

# ** truststore settings
# CONTAINER_SSL_TRUSTSTORE=
# CONTAINER_SSL_TRUSTSTORE_TYPE=
# CONTAINER_SSL_TRUSTSTORE_PASSWORD=

# CONTAINER_SSL_KEYMANAGER_PASSWORD=
# CONTAINER_SSL_EXCLUDED_CIPHER_SUITES=
# CONTAINER_SSL_EXCLUDED_PROTOCOLS=

# ** access log settings
# CONTAINER_ACCESS_LOG_DIR="logs/athenz"
# CONTAINER_ACCESS_LOG_NAME=
# CONTAINER_ACCESS_LOG_RETAIN_DAYS=
