master:
  # extraFlags: "--log_warnings=9 --skip-log-error"
  persistence:
    enabled: false
slave:
  persistence:
    enabled: false
replication:
  enabled: true
existingSecret: false
rootUser:
  # password: "mariadb"
  forcePassword: true
  injectSecretsAsVolume: false
db:
  name: 'zts_store'
  user: 'zts_admin'
  # password: 'mariadbmariadb'
  forcePassword: true
  injectSecretsAsVolume: false
replication:
  password: "replication"
  forcePassword: true
  injectSecretsAsVolume: false
volumePermissions:
    enabled: false
service:
  port: 3306
image:
  registry: docker.io
  repository: bitnami/mariadb
  debug: true
