image:
  pullPolicy: Always

password:
  jdbc: "athenz_admin"
# existingSecret: "wzzts-athenz-zts-2"
# existingTLSSecret: "wzzts-athenz-zts-tls-2"
# existingTLSCASecret: "wzzts-athenz-zts-tls-ca-2"
# existingTLSStoreSecret: "wzzts-athenz-zts-tls-store-2"

replicaCount: 1

service:
  nodePort: 30008

# extraInitContainers: |
#   - name: tls-echo
#     image: {{ template "athenz-zts.setup.image" . }}
#     imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
#     env:
#       - name: ZTS_KEYSTORE_PATH
#         value: /opt/athenz/zts/var/certs/zts_keystore.pkcs12
#       - name: ZTS_KEYSTORE_PASS
#         valueFrom:
#           secretKeyRef:
#             name: {{ template "athenz-zts.secretName" . }}
#             key: keystore
#       - name: ZTS_TRUSTSTORE_PATH
#         value: /opt/athenz/zts/var/certs/zts_truststore.jks
#       - name: ZTS_TRUSTSTORE_PASS
#         valueFrom:
#           secretKeyRef:
#             name: {{ template "athenz-zts.secretName" . }}
#             key: truststore
#     command:
#       - "/bin/sh"
#       - "-c"
#       - >-
#         keytool -list -storepass "${ZTS_KEYSTORE_PASS}" -keystore "${ZTS_KEYSTORE_PATH}"; keytool -list -storepass "${ZTS_TRUSTSTORE_PASS}" -keystore "${ZTS_TRUSTSTORE_PATH}"
#     volumeMounts:
#       - name: tls-stores
#         mountPath: /opt/athenz/zts/var/certs
