# root
# password: "mariadb_root"
# zms_admin
# password: 'athenz_admin'
# replication
# password: "replication"


master:
  # extraFlags: "--log_warnings=9 --skip-log-error"
  persistence:
    enabled: false
slave:
  persistence:
    enabled: false
replication:
  enabled: true
existingSecret: false
rootUser:
  password: "mariadb_root"
  forcePassword: true
  injectSecretsAsVolume: false
db:
  name: 'zms_server'
  user: 'zms_admin'
  password: 'athenz_admin'
  forcePassword: true
  injectSecretsAsVolume: false
replication:
  password: "replication"
  forcePassword: true
  injectSecretsAsVolume: false
# initdbScriptsConfigMap: "{{ .Release.Namespace }}-schema"
volumePermissions:
    enabled: false
service:
  port: 3306
image:
  registry: docker.io
  repository: bitnami/mariadb
  debug: true
