#
# Makefile to build Athenz UI
# Prerequisite: Node.JS development environment
#
# Copyright 2016 Yahoo Inc.
# Licensed under the Apache License, Version 2.0 - http://www.apache.org/licenses/LICENSE-2.0
#

all:
	@echo "Building Athenz UI"
	npm install
	grunt --force

clean:
	rm -rf build node_modules artifacts
