// Copyright The Athenz Authors
// Licensed under the terms of the Apache version 2.0 license. See LICENSE file for terms.

package zmssvctoken

import (
	"testing"

	"github.com/stretchr/testify/require"
)

var ecdsaPrivateKeyPEM = []byte(`-----BEGIN EC PRIVATE KEY-----
MIGkAgEBBDA27vlziu7AYNJo/aaG3mS4XPK2euiTLQDxzUoDkiMpVHRXLxSbX897
Gz7dQNFo3UWgBwYFK4EEACKhZANiAARBr6GWO6EGIV09DGInLfC/JSvPOKc26mZu
jpEdar4FkJ02OsHdtZ6AM7HgLASSBETL13Mhk8LL9qfRo+PEwLcyJnvWlDsMa3eh
Pji5iP4d9rQEOm/G9PXZ3/ZZEz5DuYs=
-----END EC PRIVATE KEY-----
`)

var ecdsaPublicKeyPEM = []byte(`-----BEGIN PUBLIC KEY-----
MHYwEAYHKoZIzj0CAQYFK4EEACIDYgAEQa+hljuhBiFdPQxiJy3wvyUrzzinNupm
bo6RHWq+BZCdNjrB3bWegDOx4CwEkgREy9dzIZPCy/an0aPjxMC3MiZ71pQ7DGt3
oT44uYj+Hfa0BDpvxvT12d/2WRM+Q7mL
-----END PUBLIC KEY-----
`)

var rsaPrivateKeyPEM = []byte(`-----BEGIN RSA PRIVATE KEY-----
MIIEpAIBAAKCAQEAxq83nCd8AqH5n40dEBMElbaJd2gFWu6bjhNzyp9562dpf454
BUSN0uF+g3i1yzcwdvADTiuExKN1u/IoGURxVCa0JTzAPJw6/JIoyOZnHZCoarcg
QQqZ56/udkSQ2NssrwGSQjOwxMrgIdH6XeLgGqVN4BoEEI+gpaQZa7rSytU5RFSG
OnZWO2Vwgs1OBxiOiYg1gzA1spJXQhxcBWw/v+YrUFtjxBKsG1UrWbnHbgciiN5U
2v51Yztjo8A1T+o9eIG90jVo3EhS2qhbzd8mLAsEhjV1sP8GItjfdfwXpXT7q2QG
99W3PM75+HdwGLvJIrkED7YRj4CpMkz6F1etawIDAQABAoIBAD67C7/N56WdJodt
soNkvcnXPEfrG+W9+Hc/RQvwljnxCKoxfUuMfYrbj2pLLnrfDfo/hYukyeKcCYwx
xN9VcMK1BaPMLpX0bdtY+m+T73KyPbqT3ycqBbXVImFM/L67VLxcrqUgVOuNcn67
IWWLQF6pWpErJaVk87/Ys/4DmpJXebLDyta8+ce6r0ppSG5+AifGo1byQT7kSJkF
lyQsyKWoVN+02s7gLsln5JXXZ672y2Xtp/S3wK0vfzy/HcGSxzn1yE0M5UJtDm/Y
qECnV1LQ0FB1l1a+/itHR8ipp5rScD4ZpzOPLKthglEvNPe4Lt5rieH9TR97siEe
SrC8uyECgYEA5Q/elOJAddpE+cO22gTFt973DcPGjM+FYwgdrora+RfEXJsMDoKW
AGSm5da7eFo8u/bJEvHSJdytc4CRQYnWNryIaUw2o/1LYXRvoEt1rEEgQ4pDkErR
PsVcVuc3UDeeGtYJwJLV6pjxO11nodFv4IgaVj64SqvCOApTTJgWXF0CgYEA3gzN
d3l376mSMuKc4Ep++TxybzA5mtF2qoXucZOon8EDJKr+vGQ9Z6X4YSdkSMNXqK1j
ILmFH7V3dyMOKRBA84YeawFacPLBJq+42t5Q1OYdcKZbaArlBT8ImGT7tQODs3JN
4w7DH+V1v/VCTl2zQaZRksb0lUsQbFiEfj+SVGcCgYAYIlDoTOJPyHyF+En2tJQE
aHiNObhcs6yxH3TJJBYoMonc2/UsPjQBvJkdFD/SUWeewkSzO0lR9etMhRpI1nX8
dGbG+WG0a4aasQLl162BRadZlmLB/DAJtg+hlGDukb2VxEFoyc/CFPUttQyrLv7j
oFNuDNOsAmbHMsdOBaQtfQKBgQCb/NRuRNebdj0tIALikZLHVc5yC6e7+b/qJPIP
uZIwv++MV89h2u1EHdTxszGA6DFxXnSPraQ2VU2aVPcCo9ds+9/sfePiCrbjjXhH
0PtpxEoUM9lsqpKeb9yC6hXk4JYpfnf2tQ0gIBrrAclVsf9WdBdEDB4Prs7Xvgs9
gT0zqwKBgQCzZubFO0oTYO9e2r8wxPPPsE3ZCjbP/y7lIoBbSzxDGUubXmbvD0GO
MC8dM80plsTym96UxpKkQMAglKKLPtG2n8xB8v5H/uIB4oIegMSEx3F7MRWWIQmR
Gea7bQ16YCzM/l2yygGhAW61bg2Z2GoVF6X5z/qhKGyo97V87qTbmg==
-----END RSA PRIVATE KEY-----
`)

var rsaPublicKeyPEM = []byte(`-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAxq83nCd8AqH5n40dEBME
lbaJd2gFWu6bjhNzyp9562dpf454BUSN0uF+g3i1yzcwdvADTiuExKN1u/IoGURx
VCa0JTzAPJw6/JIoyOZnHZCoarcgQQqZ56/udkSQ2NssrwGSQjOwxMrgIdH6XeLg
GqVN4BoEEI+gpaQZa7rSytU5RFSGOnZWO2Vwgs1OBxiOiYg1gzA1spJXQhxcBWw/
v+YrUFtjxBKsG1UrWbnHbgciiN5U2v51Yztjo8A1T+o9eIG90jVo3EhS2qhbzd8m
LAsEhjV1sP8GItjfdfwXpXT7q2QG99W3PM75+HdwGLvJIrkED7YRj4CpMkz6F1et
awIDAQAB
-----END PUBLIC KEY-----
`)

// generated by:
// openssl genpkey -algorithm EC -pkeyopt ec_paramgen_curve:P-256 -pkeyopt ec_param_enc:named_curve
var ecdsaPrivateKeyPEMInPKCS8Format = []byte(`-----BEGIN PRIVATE KEY-----
MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgTd/SNTDvns5/2c0i
5NWCXQrwC4OdfpjUU6WDCGEFUYmhRANCAAQKrQAm7ST0rDqki9G36DankKT+LM36
m/YZAaN5KC9KYjFFbT5EwGwRUiDkp7LwnrMb5ib4ppFHpbo0/kUtoxSN
-----END PRIVATE KEY-----
`)

var ecdsaPublicKeyPEMInPKCS8Format = []byte(`-----BEGIN PUBLIC KEY-----
MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAECq0AJu0k9Kw6pIvRt+g2p5Ck/izN
+pv2GQGjeSgvSmIxRW0+RMBsEVIg5Key8J6zG+Ym+KaRR6W6NP5FLaMUjQ==
-----END PUBLIC KEY-----
`)

// generated by:
// openssl genpkey -algorithm RSA -pkeyopt rsa_keygen_bits:2048 -pkeyopt rsa_keygen_pubexp:65537
var rsaPrivateKeyPEMInPKCS8Format = []byte(`-----BEGIN PRIVATE KEY-----
MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQDltv1XRkGcVFdI
1uhAo52A68qwjNnia6yQLw53HgQsFbmG2Byxsqaeab0keHFD9BEdr6FF2BLeyh1H
pq+btxlnOXUgX3uxev4FFwx9Xjt+FARapl25J3Esy4eUSoqbo0ZBtn+HKlOchhHF
rc2ieL/YvtFvWov0uWhjZnf/ilFIRrGGTPBfcP/VMZTvAyx+yInEoxbyFTfSGwz3
qvl2zp6TNbYnzLpkqq5sa3+Y0IdPuMfVQcuolFEFUT2t8FdM6LqEPnN85uplAzXN
jY5Gmyl8UrL2PDgqlZyqA0eVOBcGrtzrJH6qx9PVx0osi/RT+lJL6HuOV1UMp154
NfASUDlzAgMBAAECggEAHe95V1DABxvUnhjnflj0ExNnQBey4zdN7yI6u9otCAOy
wDhUkPGrlfRIokKR3B2nx1sWZLAyUVc8dpRpyRyU0mdh9JyM1YWmKcqlpYbMsPLx
2FBa4WCa9o/1dKU8J+kgpDqgpuAksj6kfULXi+c5dQj06RJ/L56j1GRLmgEP85+H
jk4kx668TF81lt8/7toCUG9sK5gTq5DpJ4MpL7eowRnL4Z0GKrTK0AeVhulTnSSp
kkFKK6RER3orP3/owvAP8oKl3LzI5GvI+w4ayYeyxN4Ej0UIUms1GIQRH3VYM8um
zFVjBJySdn5qb2hb+fzsM/4PKJ8FTjwvSdPRal99dQKBgQD7ucCnC+2Nap8l++bq
Y7TYhNjmrO2KVJm5BqRXJZbzD4wYApyn8xpPsy9S+BxBvunEvYga+M/Xf0U/Wyb2
14y9Ov1+CMC/BbnXnzBNGJjiXCiWm8j4MKzPX84DpMAbhiWis6ACaZjO92hFbgfF
SL+/xkH3uYs2fKNm19s5qyQ+rQKBgQDpnY51ATeUy1DGUuZW4BK+QopWyYvgKI3Z
y+CuEi9eKA7X4SXTxjqkNedIry+46OGij6x9Dpg/zL54x8269P9XNVzTAEbpvHVB
BTilJEhR7fpgxvimbn7e1Vx/jvn+UMaJwWlB9/erE7rg5kyRpo+1yj1vBfc13D3k
l421F+f8nwKBgEgNgGaQVHvhJBLUSuGWjqJXTFqi7w9kbef3Tb0gJlgGgDwzKzIr
tMFRcd9W44eyJOnKspW92Ig/hsu+xKVtR3y20O5thPZopixhBYtb2g8ZAAk0KE9a
Z2yoaKjEVLTMLiOnNMrb/QBo8vDEsPa4fyJelm1ZL8712DPM35RfN221AoGAdtk2
CSZ2XVdWH587GcVjI7H8aQyeAYsAJ2ZGRqhvuqoMax1avjNhz/qwUFT3pU2sxKPt
L64GHKcP26hibJOJd5dpQtsoOG8tA8ghOjqMJEo6j5OKGjmqh7jqFubpHc2AQ8LG
xs3dDQa7kwD2wT6IbAaYXGwfiSIjxrCnYhLobacCgYA26nh4bjNBFHHcpD+l3dXo
G1ThRdxU6m6yyIUEwnLgqVkmijd2UauDUJmr8G3A/k5KwI0QX+MKi2LK16aIdCEl
r9OhcvHFPNh36qfXsP29VFaPktwfOmCeizwbZu/aWzgSCVA/Qe90XZBujK8rP7HE
Ja3LgyuTMIL7deAllV5wPg==
-----END PRIVATE KEY-----
`)

var rsaPublicKeyPEMInPKCS8Format = []byte(`-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA5bb9V0ZBnFRXSNboQKOd
gOvKsIzZ4muskC8Odx4ELBW5htgcsbKmnmm9JHhxQ/QRHa+hRdgS3sodR6avm7cZ
Zzl1IF97sXr+BRcMfV47fhQEWqZduSdxLMuHlEqKm6NGQbZ/hypTnIYRxa3Noni/
2L7Rb1qL9LloY2Z3/4pRSEaxhkzwX3D/1TGU7wMsfsiJxKMW8hU30hsM96r5ds6e
kzW2J8y6ZKqubGt/mNCHT7jH1UHLqJRRBVE9rfBXTOi6hD5zfObqZQM1zY2ORpsp
fFKy9jw4KpWcqgNHlTgXBq7c6yR+qsfT1cdKLIv0U/pSS+h7jldVDKdeeDXwElA5
cwIDAQAB
-----END PUBLIC KEY-----
`)

func testSV(t *testing.T, s Signer, v Verifier) {
	input := `
Now is the time
for all good men
to come to the aid of the party
`
	sig, err := s.Sign(input)
	require.Nil(t, err)
	err = v.Verify(input, sig)
	require.Nil(t, err)
	input += "X"
	err = v.Verify(input, sig)
	require.NotNil(t, err)
}

func TestRSASigner(t *testing.T) {
	signer, err := NewSigner(rsaPrivateKeyPEM)
	require.Nil(t, err)
	verifier, err := NewVerifier(rsaPublicKeyPEM)
	testSV(t, signer, verifier)
}

func TestECDSASigner(t *testing.T) {
	signer, err := NewSigner(ecdsaPrivateKeyPEM)
	require.Nil(t, err)
	verifier, err := NewVerifier(ecdsaPublicKeyPEM)
	testSV(t, signer, verifier)
}

func TestECDSASignerInPKCS8(t *testing.T) {
	signer, err := NewSigner(ecdsaPrivateKeyPEMInPKCS8Format)
	require.Nil(t, err)
	verifier, err := NewVerifier(ecdsaPublicKeyPEMInPKCS8Format)
	testSV(t, signer, verifier)
}

func TestRSASignerInPKCS8(t *testing.T) {
	signer, err := NewSigner(rsaPrivateKeyPEMInPKCS8Format)
	require.Nil(t, err)
	verifier, err := NewVerifier(rsaPublicKeyPEMInPKCS8Format)
	testSV(t, signer, verifier)
}
